$ ->
  $('textarea').froalaEditor
    theme: 'custom'
    language: 'ja'
    heightMin: 200
    pastePlain: true
    toolbarButtons: [
      'undo'
      'redo'
      '|'
      'bold'
      'italic'
      'underline'
      'strikeThrough'
      '|'
      'color'
      'paragraphStyle'
      'paragraphFormat'
      'align'
      'insertHR'
      'outdent'
      'indent'
      '-'
      'insertLink'
      'insertImage'
      'clearFormatting'
      'html'
    ]
    toolbarButtonsMD: [
      'undo'
      'redo'
      '|'
      'bold'
      'italic'
      'underline'
      'strikeThrough'
      '|'
      'color'
      'paragraphStyle'
      'paragraphFormat'
      'align'
      'insertHR'
      'outdent'
      'indent'
      '-'
      'insertLink'
      'insertImage'
      'clearFormatting'
      'html'
    ]
    toolbarButtonsSM: [
      'undo'
      'redo'
      '|'
      'bold'
      'italic'
      'underline'
      'strikeThrough'
      '|'
      'color'
      'paragraphStyle'
      'paragraphFormat'
      'align'
      'insertHR'
      'outdent'
      'indent'
      '-'
      'insertLink'
      'insertImage'
      'clearFormatting'
      'html'
    ]
    toolbarButtonsXS: [
      'undo'
      'redo'
      '|'
      'bold'
      'italic'
      'underline'
      'strikeThrough'
      '|'
      'color'
      'paragraphStyle'
      'paragraphFormat'
      'align'
      'insertHR'
      'outdent'
      'indent'
      '-'
      'insertLink'
      'insertImage'
      'clearFormatting'
      'html'
    ]
    imageAltButtons: [ 'imageBack' ]
    imageUploadURL: '/media/upload.json'
    imageUploadMethod: 'POST'
    imageMaxSize: 1024 * 1024 * 5
    imageInsertButtons: [
      'imageUpload'
      'imageByURL'
    ]
    imageDefaultWidth: 300
    imageDefaultAlign: 'left'
    imageAllowedTypes: [
      'jpeg'
      'jpg'
      'png'
    ]
    imageEditButtons: [
      'imageAlign'
      'imageAlt'
      'imageSize'
      'imageRemove'
      '-'
      'imageLink'
      'linkOpen'
      'linkEdit'
      'linkRemove'
    ]
    fileUploadURL: '/pictures/upload.json'
    fileUploadMethod: 'POST'
    fileMaxSize: 1024 * 1024 * 5
    charCounter: true
